USE [master]
GO

/****** Object:  Database [eduardo_guedes]    Script Date: 16/06/2020 23:39:21 ******/
CREATE DATABASE [eduardo_guedes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'eduardo_guedes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\eduardo_guedes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'eduardo_guedes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\eduardo_guedes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [eduardo_guedes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [eduardo_guedes] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [eduardo_guedes] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [eduardo_guedes] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [eduardo_guedes] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [eduardo_guedes] SET ARITHABORT OFF 
GO

ALTER DATABASE [eduardo_guedes] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [eduardo_guedes] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [eduardo_guedes] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [eduardo_guedes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [eduardo_guedes] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [eduardo_guedes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [eduardo_guedes] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [eduardo_guedes] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [eduardo_guedes] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [eduardo_guedes] SET  DISABLE_BROKER 
GO

ALTER DATABASE [eduardo_guedes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [eduardo_guedes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [eduardo_guedes] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [eduardo_guedes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [eduardo_guedes] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [eduardo_guedes] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [eduardo_guedes] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [eduardo_guedes] SET RECOVERY FULL 
GO

ALTER DATABASE [eduardo_guedes] SET  MULTI_USER 
GO

ALTER DATABASE [eduardo_guedes] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [eduardo_guedes] SET DB_CHAINING OFF 
GO

ALTER DATABASE [eduardo_guedes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [eduardo_guedes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [eduardo_guedes] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [eduardo_guedes] SET QUERY_STORE = OFF
GO

ALTER DATABASE [eduardo_guedes] SET  READ_WRITE 
GO


